# Generated by Django 5.1.5 on 2025-02-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tct',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tct',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
